### PR TITLE
feat(ytm): Re-implement auth with cookie and oauth

### PR DESCRIPTION
**Pull request by FoxxMD**
## Checklist before requesting a review

- [x] I have read the [contributing guidelines.](../CONTRIBUTING.md)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Describe your changes

Youtube TV seems no longer have scope for reading history or account details. Cookies may work and custom oauth seems most stable based on reporting from LuanRT/YouTube.js#803

* Re-implement cookie auth
* Implement custom OAuth Client auth based on [example](https://github.com/LuanRT/YouTube.js/blob/main/examples/auth/custom-oauth2-creds/index.ts)

## TODO

- [x] Add FAQ entry for common YTM auth issues, refer to [yt-dlp known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) for some general guidance
  - [x] Add [guidance from yt-dlp about exporting cookies](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies)
- [x] Update YTM config with cookie and oauth setup

## Issue number and link, if applicable

#195 
#229
#203

### CODE REVIEW

**Comment by FoxxMD** [comment]
# Cookie Auth

Works _for now_ but this is likely to be the **least stable option and is not recommended.**

Use instructions from https://github.com/patrickkfkan/Volumio-YouTube.js/wiki/How-to-obtain-Cookie or https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html#copy-authentication-headers to get the **Cookie** value.

It is recommended to [get the cookie from an Incognito/Private Session](https://github.com/LuanRT/YouTube.js/issues/803#issuecomment-2504032666) to limit the chance the session is invalidated from normal browsing.

Add the cookie to your `ytmusic.json` config in `data`: 

```json
{
  "type": "ytmusic",
  "enable": true,
  "name": "MyYTM",
  "data": {
    "cookie": "__Secure-1PSIDTS=sidts-CjEB3EgAEvCd-......"
  },
  "options": {
    "logAuthUpdateChanges": true,
    "logDiff": true
  }
}
```

# Custom OAuth

This is likely to be more stable but takes much more setup than cookies. **If you can, this is the recommended approach.**

[Base on the instructions from here...](https://github.com/LuanRT/YouTube.js/issues/803#issuecomment-2479689924)

* Create a google cloud account and a new project
* Go to APIs and services.
  * Configure the OAuth consent screen
    * Use the old experience if possible, new seems bugged (for me)
      * If new is unavoidable then do not fill out any branding and under Authorized Domains you can delete the empty one (in order to save)
    * Credentials
      * Create Credentials -> choose "OAuth client ID"
        *  Application Type is **Web Application**
        * **Name** is whatever you want, leave Authorization Javascript origins blank
        * Authorized redirect URIs
          * This must be **exactly** the same as what is displayed in MS! For now leave it blank so we can generate it from MS first
       * Create
         * In the newly created client popup save the **Client ID** and **Client Secret**, then copy them into `ytmusic.json`

```json
{
  "type": "ytmusic",
  "enable": true,
  "name": "MyYTM",
  "data": {
    "clientId": "8910....6jqupl.apps.googleusercontent.com",
    "clientSecret": "GOCSPX-WGXL6BSuQ343..."
  },
  "options": {
    "logAuthUpdateChanges": true,
    "logDiff": true
  }
}
```

**NOTE:** If you have an existing YTM credentials folder in your `/config` directory rename or delete it now. It would look like `yti-MyYTM` (or whatever your source name is)

Now, start MS and during the YTMusic startup it will log something like this:

```
Using Custom OAuth Client with Redirect URI: http://localhost:9078/api/ytmusic/callback?name=MyYTM
```

If the beginning of the URL (before `api`) is EXACTLY how you would reach the MS dashboard from your browser (EX `http://localhost:9078`) then edit your google oauth client section for `Authorized redirect URIs` and add the URL MS has displayed.

If it is NOT EXACTLY the same you either need to set MS's [base url](https://foxxmd.github.io/multi-scrobbler/docs/configuration/#base-url) or you can provide a redirect URI for MS to use by setting it in `ytmusic.json`.

The two parts of the URL that must be the same:

* it must end in `ytmusic/callback`
* It must include `name=[NameOfSource]` in the query string

```json
{
  "type": "ytmusic",
  "enable": true,
  "name": "MyYTM",
  "data": {
    "clientId": "8910....6jqupl.apps.googleusercontent.com",
    "clientSecret": "GOCSPX-WGXL6BSuQ343...",
   "redirectUri": "http://my.custom.domain/api/ytmusic/callback?name=MyYTM"
  },
  "options": {
    "logAuthUpdateChanges": true,
    "logDiff": true
  }
}
```

**Comment by jrlebbs** [comment]
Good evening,

Moving to this thread, as requested.

First test with the cookie approach: worked as seamless as before.

Second test with the new oauth approach: error once authorizing past the oauth page "No page for /ytmusic/callback%3Fname=MyYTM exists!"

I did initially try the custom URI with my duckdns domain, but it stalled out entirely, so I reverted just to using the localhost to test this configuration.

I do notice that my redirect URI is "...callback%#Fname%" and your example is "callback?name". Maybe that contributes?

Let me know what else I can provide/test help!

**Comment by FoxxMD** [comment]
@jrlebbs can you give me more specifics about the conditions these things happened under?

Please provide the `redirectUri` you are using in `ytmusic.json` (if any) and also the log output containing the uri (`Using Custom OAuth Client with Redirect URI: ...`) for both tests that failed, thanks.

**Comment by xathon** [comment]
Just pulled the latest image. 

Can confirm that the cookie authentication works.

Notes while I set up Oauth:

The Google Cloud console tells me that the old experience "will only be available for a few more days. "

Getting a 403 when I use a brand account for YTM that's associated with my Google account. Had to add myself to the test users.

Now the oauth itself seems to work, but the callback gives a 404 page on my multiscrobbler instance. Log output (replaced my domain with example.com):
```
[2024-12-04 23:18:04.836 +0100] DEBUG  : [App] [API] Server received GET request from ::ffff:172.19.0.5 (192.168.10.20) (UA: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0) to unknown route: /api/ytmusic/callback%3Fname=YTMusic?code=4/0AeanS0aF8UsvWVfH7vnjpw67iNw30fccJ9NCmA2xvMHwT2SSZHRWBNwWh634G3FyGM9q1g&scope=https://www.googleapis.com/auth/youtube.force-ssl%20https://www.googleapis.com/auth/youtube-paid-content%20https://www.googleapis.com/auth/youtube%20https://www.googleapis.com/auth/accounts.reauth
[2024-12-04 23:17:50.881 +0100] ERROR  : [App] [Sources] [Ytmusic - YTMusic] Authentication test failed!
Error: Authentication test failed!
    at YTMusicSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:235:31)
    at YTMusicSource.reauthenticate (CWD/src/backend/sources/YTMusicSource.ts:138:9)
    at <anonymous> (CWD/src/backend/server/auth.ts:56:17)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: Sign in using https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=http%3A%2F%2Fgdata.youtube.com%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.force-ssl%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube-paid-content%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&include_granted_scopes=true&prompt=consent&response_type=code&client_id=547627672513-4t2drr32djjstof7eiqnofif6318lhtm.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fscrobbler.home.example.com%2Fapi%2Fytmusic%2Fcallback%253Fname%3DYTMusic
    at YTMusicSource.doAuthentication (CWD/src/backend/sources/YTMusicSource.ts:223:27)
    at YTMusicSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:229:27)
    at YTMusicSource.reauthenticate (CWD/src/backend/sources/YTMusicSource.ts:138:9)
    at <anonymous> (CWD/src/backend/server/auth.ts:56:17)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
[2024-12-04 23:17:50.879 +0100] INFO   : [App] [Sources] [Ytmusic - YTMusic] Using Custom OAuth Client with Redirect URI: https://scrobbler.home.example.com/api/ytmusic/callback%3Fname=YTMusic
```

According to the Google Cloud UI, the OAuth token is being passed. The Redirect URI that the log shows is also what I put in the credentials tab:
image

But in the end, it's not working.

**Comment by FoxxMD** [comment]
@xathon thanks for the feedback. Can you try replacing `%3F` in your Authorized redirect URI with `?` and see if that makes a difference?

**Comment by xathon** [comment]
Forgot to mention, I actually did that. Google then told me that the redirect URL doesn't match.

**Comment by bockbilbo** [comment]
Hey @FoxxMD, I am having the same behavior as @xathon .

After following the steps to set up Oauth, and clicking auth, I got to the Google page for the permissions, then accepted the risk of the testing app, but then got redirected to a url within my MS installation saying "Not Found" (aka 400). I then modified the %3F with ? and now google is complaining about the url not matching the Authorized redirect URIs. 

So, I went back to the Google console, and added a second URL under Authorized redirect URIs with the URL using the question mark. After that, the MS page I am redirected to from the Google authorization process says "OK".

I can se the logs now showing tracks discovered in YT Music!

**Comment by bockbilbo** [comment]
I can confirm that MS is now scrobbling YTMusic again! Thanks a lot @FoxxMD !

**Comment by FoxxMD** [comment]
> Google then told me that the redirect URL doesn't match.
> ...
> So, I went back to the Google console, and added a second URL under Authorized redirect URIs with the URL using the question mark.

I did find that after changing the auth URL it takes google cloud _at least_ a few minutes for the change to take affect.

I'm trying to figure out why MS is displaying `%3F` to ya'll but it should be showing `?` (and it shows `?` to me in dev).

**Comment by xathon** [comment]
Can confirm, that works! Thanks!

**Comment by trevornk** [comment]
I was having the same issues as above users when trying to use oauth yesterday.  Today I skipped oauth and went right to cookie auth and everything worked great.

**Comment by jrlebbs** [comment]
> @jrlebbs can you give me more specifics about the conditions these things happened under?
> 
> Please provide the `redirectUri` you are using in `ytmusic.json` (if any) and also the log output containing the uri (`Using Custom OAuth Client with Redirect URI: ...`) for both tests that failed, thanks.
> 
> EDIT: I have pushed a change to the default redirectUri generation that may fix your issue. Please pull the latest `pr-236` image and retry (and include logs/config!)

Here's my update.

Pulled the latest build of pr-236. 

Attempt 1: No custom URI, just used the localhost URI generated by MS. Worked amazing!

Attempt 2: custom domain URI: `"http://customdomainhere.duckdns.org:9078/api/ytmusic/callback?name=MyYTM"`
clicked "re-authenticate"
re-routes to this URL: http://customdomainhere.duckdns.org:9078/api/source/undefined
Error: "Not Found"



confirmed that i put it in the google cloud redirect uri as well:

image



Verbose logs attached.
[log_customdomain.txt](https://github.com/user-attachments/files/18028209/log_customdomain.txt)

**Comment by FoxxMD** [comment]
The newest image should now allow re-authenticating and will also verify the validity of a custom redirect uri

**Comment by jrlebbs** [comment]
> The newest image should now allow re-authenticating and will also verify the validity of a custom redirect uri

it worked!! no issues at this point!

**Comment by FoxxMD** [comment]
Newest image supports ENV config:

| Environmental Variable | Required? | Default |                  Description                  |
|------------------------|-----------|---------|-----------------------------------------------|
| YTM_COOKIE             | No        |         | Value for Cookie Authentication               |
| YTM_CLIENT_ID          | No        |         | Client ID for OAuth Athentication             |
| YTM_CLIENT_SECRET      | No        |         | Client Secret for OAuth Athentication         |
| YTM_REDIRECT_URI       | No        |         | A custom redirect URI for OAuth Athentication |
| YTM_LOG_DIFF           | No        | false   | Log YTM history changes                       |

**Comment by tylermiranda** [comment]
What a PIA...That being said..Thank you @FoxxMD for your work on this. I got mine working...

**Pull request merged**
