### PR TITLE
build arm [closes #45]

### LINKED ISSUE #45: ARM docker image builds
Are you interested in ARM builds? I've implemented those for maloja and it looks like you have almost the same actions file so it should be piece of cake to implement it into your workflow as well.

### PR DESCRIPTION
**Pull request by northys**
https://github.com/northys/multi-scrobbler/runs/6181049880
https://github.com/northys/multi-scrobbler/pkgs/container/multi-scrobbler

If you want I can change hash version of used actions to their major version but maloja owner required hashes for security and I saw that you used exact hash for docker login as well so I kept hash version in all actions.

### CODE REVIEW

**Comment by FoxxMD** [comment]
This is great! Can you change PR to merge into `develop` instead of `master`?

**Comment by northys** [comment]
done

**Comment by northys** [comment]
I think that maybe I can remove the caching stuff as well... The build took less than 2 minutes, there is tmp workaround and also the cache works only sometimes...

**Comment by northys** [comment]
Yup I'll drop it. Wait a second.

**Comment by northys** [comment]
done - https://github.com/northys/multi-scrobbler/runs/6181670442?check_suite_focus=true

**Comment by FoxxMD** [comment]
Thanks on behalf of all the Raspi users :)

**Pull request merged**
