### PR TITLE
feat(youtube)!: Use oauth-based api library for better stability

### LINKED ISSUE #158: YouTube Music auth fails after 30 minutes
**Describe the bug**
This is more of an FYI report since it's hardly a bug- more of an issue with YouTube Music authentication. I've noticed that the cookie seems to change with 30-60 minute intervals, whereas the scrobbler is no longer able to authenticate and fetch the play history.

Excerpt of the part of the cookie changing:

image

Doing a copy+paste of the new cookie to config.json makes the authentication work again for ~30 minutes.

The behaviour is the same regardless if using the browser to stream, 3:rd party desktop app or mobile app.

**To Reproduce**
1. Multi-scrobbler (local) with ytmusic set up
2. Play music for ~30 minutes

**Expected behavior**
To have the session stay alive longer, I'm guessing that since I'm not logged out of any of the apps/browser that perhaps it's some kind of token refresh causing the auth error in multi-scrobbler

**Logs**
```
[2024-06-13 14:11:55.840 +0200] ERROR  : [App] [Sources] [Ytmusic - MyYTMusic] Authentication test failed!
Error: Authentication test failed!
    at YTMusicSource.testAuth (file://CWD/src/backend/common/AbstractComponent.ts:1:2290)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YTMusicSource.initialize (file://CWD/src/backend/common/AbstractComponent.ts:1:569)
    at async ScrobbleSources.addSource (file://CWD/src/backend/sources/ScrobbleSources.ts:4:2751)
    at async ScrobbleSources.buildSourcesFromConfig (file://CWD/src/backend/sources/ScrobbleSources.ts:4:352)
    at async file://CWD/src/backend/index.ts:1:2925
caused by: Error: Could not send the specified request to browse. Status code: 401
    at v.<anonymous> (CWD/node_modules/youtube-music-ts-api/build/exports.js:3:52363)
    at p (CWD/node_modules/youtube-music-ts-api/build/exports.js:3:43721)
    at Generator.<anonymous> (CWD/node_modules/youtube-music-ts-api/build/exports.js:3:45067)
    at Generator.next (CWD/node_modules/youtube-music-ts-api/build/exports.js:3:44150)
    at a (CWD/node_modules/youtube-music-ts-api/build/exports.js:3:50795)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-13 14:11:55.839 +0200] ERROR  : [App] [Sources] [Ytmusic - MyYTMusic] Authentication failed with the given credentials. Verify your cookie and authUser are correct. | Error => Could not send the specified request to browse. Status code: 401
[2024-06-13 14:11:55.810 +0200] DEBUG  : [App] [Sources] [Ytmusic - MyYTMusic] Connection check was not required.
[2024-06-13 14:11:55.809 +0200] DEBUG  : [App] [Sources] [Ytmusic - MyYTMusic] No required data to build.
[2024-06-13 14:11:55.809 +0200] DEBUG  : [App] [Sources] [Ytmusic - MyYTMusic] Attempting to initia
```

**Versions (please complete the following information):**
- multi-scrobbler: [e.g. 0.7.1 locally as a service using pm2, ytMusicDebug branch]

### LINKED ISSUE #195: New YTMusic Cookie Format?
[Please check the FAQ](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md) before submitting a bug report.

**Describe the bug**
YouTube Music stopped authenticating as a source about 3 days ago. Logged in following the guide and the cookie now starts with "HSID" instead of "SID"

**To Reproduce**
1. Follow the steps on the config guide: https://foxxmd.github.io/multi-scrobbler/docs/configuration/#youtube-music

**Expected behavior**
The cookie should auth YTMusic.

**Logs**
If possible reproduce the issue with [debug logging ON](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md#turn-on-debug-logging)

```
2024-09-27T23:27:29-06:00 debug : [Notifiers] [Ntfy - Multi-Scrobbler] Pushed notification.
2024-09-27T23:27:28-06:00 error : [Sources] [Ytmusic - YTMusic] Cannot start polling because source is not authenticated correctly.
2024-09-27T23:27:28-06:00 info : [App] Server started at http://localhost:9078
2024-09-27T23:27:27-06:00 warn : [Sources] ytmusic (YTMusic) source auth failed.
2024-09-27T23:27:26-06:00 debug : [Sources] Checking ytmusic (YTMusic) source auth...
2024-09-27T23:27:26-06:00 info : [Sources] ytmusic (YTMusic) source initialized
2024-09-27T23:27:26-06:00 debug : [Sources] Attempting ytmusic (YTMusic) initialization...
2024-09-27T23:27:26-06:00 debug : [Sources] (YTMusic) Constructing ytmusic source
2024-09-27T23:27:26-06:00 debug : [Sources] listenbrainz has 'configureAs: client' so will skip adding as a source
2024-09-27T23:27:26-06:00 debug : [Sources] lastfm has 'configureAs: client' so will skip adding as a source
2024-09-27T23:27:26-06:00 info : [Scrobblers] listenbrainz (brainz) client auth OK
2024-09-27T23:27:25-06:00 debug : [Scrobblers] Checking listenbrainz (brainz) client auth...
2024-09-27T23:27:25-06:00 info : [Scrobblers] listenbrainz (brainz) client initialized
2024-09-27T23:27:25-06:00 debug : [Scrobblers] Attempting listenbrainz (brainz) initialization...
2024-09-27T23:27:25-06:00 debug : [Scrobblers] Constructing listenbrainz (brainz) client...
2024-09-27T23:27:25-06:00 info : [Scrobblers] lastfm (myLastFm) client auth OK
2024-09-27T23:27:25-06:00 info : [API - Lastfm - myLastFm] Client authorized for user jrlebbs
2024-09-27T23:27:25-06:00 debug : [Scrobblers] Checking lastfm (myLastFm) client auth...
2024-09-27T23:27:25-06:00 info : [Scrobblers] lastfm (myLastFm) client initialized
2024-09-27T23:27:25-06:00 debug : [Scrobblers] Attempting lastfm (myLastFm) initialization...
2024-09-27T23:27:25-06:00 debug : [Scrobblers] Constructing lastfm (myLastFm) client...
2024-09-27T23:27:25-06:00 info : [Notifiers] [Ntfy - Multi-Scrobbler] Initialized. Found Ntfy server
.
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: unsure, installed about a year ago and not upgraded since. request help on how to find, if required
-- running on windows

**Additional context**
I have tried several ways, reboots, etc. to get this to work. I suspect the cookie format has changed and I'm happy to provide more cookie details, just unsure of what's secure or not to be careful with.

Happy to help in any way!

### PR DESCRIPTION
**Pull request by FoxxMD**
## Checklist before requesting a review

- [x] I have read the [contributing guidelines.](../CONTRIBUTING.md)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Describe your changes

Migrate from [youtube-music-ts-api](https://github.com/nickp10/youtube-music-ts-api), which only supports cookie-based auth -- to [Youtube.js](https://ytjs.dev/), which uses oauth auth.

### Usage

Start multi-scrobbler with any existing YTM configuration. A log statement will prompt the user to visit a URL with a code (or it can be accessed from the dashboard)

```
[2024-10-09 15:24:17.358 -0400] INFO   : [App] [Sources] [Ytmusic - MyYTM] ERROR: Sign in with the code 'CLV-KFA-BVKY' using the authentication link on the dashboard or https://www.google.com/device
```

Visit the URL and enter the code, then finish the auth flow. Afterwards, refresh the dashboard and click **Start** on the Idle YTM source to start polling.

## Issue number and link, if applicable

* Fixes #195 missing (404) history endpoint which only appear when using cookies
* Might fix #158 due to using a different authentication method

### CODE REVIEW

**Comment by xathon** [comment]
I think something in 671056d broke logging a lot :D  it seems that for everything it does, it creates a log file. My logs directory immediately fills up with thousands of mostly empty log files.

**Comment by xathon** [comment]
Ah, I didn't want to raise a separate issue since I had the PR image running and thought it came from that.

But yay, DST magic at it again :D

**Comment by FoxxMD** [comment]
@fluffyclaws @xathon other than the DST issue how is this PR working for you? Have you experienced any of the issues reported in #195 (duplicate scrobbles) after using it? I need more feedback from users before I can merge this.

**Comment by xathon** [comment]
I _think_ there was something. I'll check on it in the next couple of days and report back.

**Comment by FoxxMD** [comment]
The latest `pr-203` docker image has the DST fix incorporated.

**Comment by xathon** [comment]
Can confirm that there are no duplicate scrobbles the past few days. Only thing that I see is that the timestamps don't appear in the web log, the lines look like this:
```
Ad Infinitum - Aftermath --- Abyss @ N/A (Today)
```

**Comment by FoxxMD** [comment]
Thanks for the feedback. The missing timestamps are intentional since MS is showing you what info it received from YTM (no timestamps).

**Comment by xathon** [comment]
Hey, sorry, I have to retract my confirmation. I checked the wrong place, since in the web log of multiscrobbler they show up as single, but in Maloja they're duplicated. Excerpt from the log when this happens:
```
[2024-11-02 17:15:25.296 +0100] DEBUG : [App] [Sources] [Ytmusic - YT Music] Refreshing recently played

[2024-11-02 17:15:17.460 +0100] DEBUG : [App] [Scrobblers] [Maloja - unnamed-mlj] Raw Payload:

[2024-11-02 17:15:17.459 +0100] INFO : [App] [Scrobblers] [Maloja - unnamed-mlj] Scrobbled (New) => (YTMusic) 妖精帝國 - IRON ROSE @ 2024-11-02T17:15:01+01:00 (S)

[2024-11-02 17:15:16.283 +0100] DEBUG : [App] [Sources] [Ytmusic - YT Music] Last activity was at 2024-11-02T17:15:01+01:00 | Next check interval: 10.00s

[2024-11-02 17:15:16.282 +0100] INFO : [App] [Sources] [Ytmusic - YT Music] Discovered => 妖精帝國 - IRON ROSE @ 2024-11-02T17:15:01+01:00 (S)

[2024-11-02 17:15:15.417 +0100] DEBUG : [App] [Scrobblers] [Maloja - unnamed-mlj] Raw Payload:

[2024-11-02 17:15:15.416 +0100] INFO : [App] [Scrobblers] [Maloja - unnamed-mlj] Scrobbled (New) => (YTMusic) 妖精帝國 - Paradiso≒Inferno @ 2024-11-02T17:15:01+01:00 (S)

[2024-11-02 17:15:15.392 +0100] DEBUG : [App] [Scrobblers] [Maloja - unnamed-mlj] Found 40 recent scrobbles

[2024-11-02 17:15:15.380 +0100] DEBUG : [App] [Scrobblers] [Maloja - unnamed-mlj] Refreshing recent scrobbles

[2024-11-02 17:15:15.378 +0100] DEBUG : [App] [Scrobblers] [Maloja - unnamed-mlj] [Upstream Refresh] Should refresh => newest queued scrobble playDate is newer than last refresh

[2024-11-02 17:15:14.850 +0100] DEBUG : [App] [Sources] [Ytmusic - YT Music] Refreshing recently played

[2024-11-02 17:15:14.849 +0100] DEBUG : [App] [Sources] [Ytmusic - YT Music] Last activity was at 2024-11-02T17:15:01+01:00 | Next check interval: 10.00s

[2024-11-02 17:15:14.846 +0100] INFO : [App] [Sources] [Ytmusic - YT Music] Discovered => 妖精帝國 - Paradiso≒Inferno @ 2024-11-02T17:15:01+01:00 (S)

[2024-11-02 17:15:04.844 +0100] INFO : [App] [Sources] [Ytmusic - YT Music] Potential plays were discovered close to polling interval! Delaying scrobble clients refresh by 10 seconds so other clients have time to scrobble first


```

**Comment by FoxxMD** [comment]
For anyone having auth and history fetching issues: please try out the new authentication methods detailed in [#236](https://github.com/FoxxMD/multi-scrobbler/pull/236#issuecomment-2515572189) using the docker image `foxxmd/multi-scrobbler:pr-236`

If you try out the new docker image please post any issues you have with it in the issue for #236 instead of this one so I can better keep track of things, thanks.

**Pull request merged**
